name: Lint Check

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to run flake8"
        default: "3.13"
        type: string
        required: false

jobs:

  formatting:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version}}  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
          
      - name: Run black
        run: |
          black --check src/
          black --check tests/

      - name: Run isort
        run: |
          isort --check-only src/
          isort --check-only tests/

  lint:
    runs-on: ubuntu-latest
    
    steps:   
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version}}  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          
      - name: Run flake8
        run: |
          flake8 src/
          flake8 tests/
