name: Lint Check

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to run ruff"
        default: "3.13"
        type: string
        required: false

jobs:

  lint:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv add ruff
          
      - name: Run ruff check
        run: |
          uv run ruff check . --output-format=github

      - name: Run ruff format check
        run: |
          uv run ruff format --check .

